- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: what is your username?
    private: false
  tasks:
  - name: print credentials
    ansible.builtin.debug:
      msg: "Hello,username is: {{ username }}"